apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotel-frontend
  template:
    metadata:
      labels:
        app: hotel-frontend
    spec:
      containers:
      - name: hotel-frontend
        image: kastrov/hotel-frontend:IMAGE_TAG
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5