apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: default
spec:
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP