apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: default
spec:
  selector:
    app: review-service
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
  type: ClusterIP